[package]
name = "loomiquu/tether"
version = "0.1.0-dev.2"
description = "Module based Service framework"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

license = "MIT"
authors = ["Loomiquu"]

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
